baseURL = "https://sapronov.me/"


builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Alexander Sapronov"
title = "Alexander Sapronov"

theme = "custom-hugo-goa"
googleAnalytics = "UA-53909016-1"

showcomments = false
showpagemeta = false

enableRobotsTXT = true

## Site Settings
[params]
author = "Александр Сапронов"
intro = "IT Manager (Руководитель IT/CTO)"
description = "9 лет опыта в IT, работал в МТС, МТС, Avito, Welltory и других компаниях"
job_want = "Ищу "
resume_ru = "/resume/resume_ru.pdf"
resume_long_ru = "/resume/resume_long_ru.pdf"
authorimage = "headshot.png"
dateformat = "Jan 26, 2020"
long_description = "show"

## Site Meta Settings
[params.meta]
description = "IT Manager (Руководитель IT/CTO). 9 лет опыта в IT, работал в МТС, МТС, Avito, Welltory и других"
keywords = "engineering,manager,developer,welltory,about,avito,mts,mts"

## Social Accounts
[params.social]
github = "axsapronov"
instagram = "axsapronov"
linkedin = "axsapronov"
twitter = "axsapronov"
facebook = "axsapronov"
telegram = "axsapronov"
email = "a@sapronov.me"

## Extras
[params.extra]
poweredby = false
highlightjs = true
socialmarkup = true

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "coderag"
    identifier = "coderag"
    weight = 300
    url = "/coderag/"